---
id: rubykaigi-2024-followup
base_name: slide
tags: ["ruby", "tls"]
presentation_date: 2024-08-31
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: ["MIT"]
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri: https://github.com/unasuke/rubykaigi-2024-followup
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
